"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-06 23:52:39.502678
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "party",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=200), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("national_id", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("street", sa.String(length=200), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "policy",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("product_code", sa.String(length=20), nullable=False),
        sa.Column("holder_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("tariff_version", sa.String(length=40), nullable=False),
        sa.Column("conditions_version", sa.String(length=40), nullable=False),
        sa.Column("risk", sa.JSON(), nullable=False),
        sa.Column("net_premium", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tax", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("gross_premium", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["holder_id"],
            ["party.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    with op.batch_alter_table("policy", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_policy_holder_id"), ["holder_id"], unique=False)

    op.create_table(
        "claim",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("peril", sa.String(length=32), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("claimed_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("payable_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("approved_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("coverage", sa.JSON(), nullable=True),
        sa.Column("queue", sa.String(length=32), nullable=True),
        sa.Column("extraction", sa.JSON(), nullable=True),
        sa.Column("triage", sa.JSON(), nullable=True),
        sa.Column("summary", sa.JSON(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policy.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    with op.batch_alter_table("claim", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_claim_policy_id"), ["policy_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_claim_status"), ["status"], unique=False)

    op.create_table(
        "agent_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("agent", sa.String(length=50), nullable=False),
        sa.Column("agent_version", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("turns", sa.Integer(), nullable=False),
        sa.Column("tool_calls", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claim.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_run", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_run_claim_id"), ["claim_id"], unique=False)

    op.create_table(
        "claim_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=24), nullable=True),
        sa.Column("to_status", sa.String(length=24), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claim.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("claim_event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_claim_event_claim_id"), ["claim_id"], unique=False)

    op.create_table(
        "document",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claim.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("claim_id", "sha256"),
    )
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_document_claim_id"), ["claim_id"], unique=False)

    op.create_table(
        "draft_review",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("agent", sa.String(length=50), nullable=False),
        sa.Column("verdict", sa.String(length=8), nullable=False),
        sa.Column("corrections", sa.JSON(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("reviewer", sa.String(length=100), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claim.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("draft_review", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_draft_review_claim_id"), ["claim_id"], unique=False)

    op.create_table(
        "job",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("queue", sa.String(length=16), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("run_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claim.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_claim_id"), ["claim_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_run_after"), ["run_after"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_status"))
        batch_op.drop_index(batch_op.f("ix_job_run_after"))
        batch_op.drop_index(batch_op.f("ix_job_claim_id"))

    op.drop_table("job")
    with op.batch_alter_table("draft_review", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_draft_review_claim_id"))

    op.drop_table("draft_review")
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_claim_id"))

    op.drop_table("document")
    with op.batch_alter_table("claim_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claim_event_claim_id"))

    op.drop_table("claim_event")
    with op.batch_alter_table("agent_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_run_claim_id"))

    op.drop_table("agent_run")
    with op.batch_alter_table("claim", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claim_status"))
        batch_op.drop_index(batch_op.f("ix_claim_policy_id"))

    op.drop_table("claim")
    with op.batch_alter_table("policy", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_policy_holder_id"))

    op.drop_table("policy")
    op.drop_table("party")
    # ### end Alembic commands ###
